
= Проект тестирования веб-приложения на основе Selenium WebDriver и TestNG

== Описание проекта
Этот проект предназначен для автоматизации тестирования веб-приложения с использованием Selenium WebDriver, TestNG и Allure для отчетности. В проекте используются паттерны Page Object Model (POM) и Utility Classes для обеспечения структурированной и повторно используемой архитектуры тестов.

== Структура проекта
Проект содержит следующие пакеты и классы:

* `pages` - Содержит классы, представляющие страницы веб-приложения (Page Objects).
* `AddCustomerPage` - Класс для взаимодействия со страницей добавления клиента.
* `CustomersPage` - Класс для взаимодействия со страницей просмотра клиентов.
* `HomePage` - Класс для взаимодействия с главной страницей.

* `utils` - Содержит вспомогательные классы, предоставляющие общие функции и утилиты.
* `Constants` - Класс с константными значениями, используемыми в проекте.
* `PropertyProvider` - Класс для работы с конфигурационными свойствами.
* `TestDataGenerator` - Класс для генерации тестовых данных.
* `Wait` - Класс для обработки явных ожиданий (waits) в WebDriver.

* `test` - Содержит тестовые классы, выполняющие различные проверки.
* `AddCustomerTest` - Тест добавления нового клиента.
* `DeleteCustomerTest` - Тест удаления клиента.
* `SortCustomersTest` - Тест сортировки клиентов.

== Описание классов

=== 1. AddCustomerPage
`AddCustomerPage` представляет собой страницу добавления клиента и обеспечивает методы для взаимодействия с элементами этой страницы.

**Основные методы:**
- `enterFirstName(String firstName)` - вводит имя клиента.
- `enterLastName(String lastName)` - вводит фамилию клиента.
- `enterPostCode(String postCode)` - вводит почтовый код клиента.
- `submit()` - нажимает кнопку "Добавить клиента".

=== 2. CustomersPage
`CustomersPage` представляет страницу, на которой отображается список клиентов, и предоставляет методы для сортировки и удаления клиентов.

**Основные методы:**
- `getCustomerNames()` - возвращает список имен всех клиентов.
- `sortCustomersByName()` - сортирует клиентов по имени.
- `deleteCustomerByName(String name)` - удаляет клиента с указанным именем.

=== 3. HomePage
`HomePage` представляет главную страницу приложения и содержит методы для перехода к страницам добавления и просмотра клиентов.

**Основные методы:**
- `clickAddCustomer()` - переходит к странице добавления клиента.
- `clickCustomers()` - переходит к странице просмотра клиентов.

=== 4. TestDataGenerator
`TestDataGenerator` - это утилитный класс для генерации случайных данных для тестирования.

**Основные методы:**
- `generatePostCode()` - генерирует случайный почтовый код.
- `generateFirstName(String postCode)` - генерирует имя на основе почтового кода.

=== 5. Wait
`Wait` - утилитный класс для обработки явных ожиданий в Selenium WebDriver.

**Основные методы:**
- `waitUntilVisible(WebDriver driver, WebElement webElement)` - ожидает видимости элемента.
- `waitUntilClickable(WebDriver driver, WebElement webElement)` - ожидает, пока элемент станет кликабельным.

=== 6. PropertyProvider
`PropertyProvider` - утилитный класс для загрузки и получения свойств из файла `config.properties`.

**Основной метод:**
- `getProperty(String key)` - возвращает значение свойства по ключу.

=== 7. Constants
`Constants` - класс, содержащий константы, используемые в проекте.

**Основные константы:**
- `BASE_URL` - базовый URL веб-приложения.
- `CUSTOMER_ADDED_MESSAGE` - сообщение об успешном добавлении клиента.

== Тестовые классы

=== AddCustomerTest
Тест проверяет возможность добавления нового клиента. Использует аннотации Allure `@Description`, `@Step` и `@Severity` для улучшенной отчетности.

**Основные шаги:**
1. Ввод данных клиента (имя, фамилия, почтовый код).
2. Отправка формы.
3. Проверка сообщения в алерте.

=== DeleteCustomerTest
Тест проверяет удаление клиента, длина имени которого ближе всего к среднеарифметической длине всех имен.

**Основные шаги:**
1. Получение списка имен клиентов.
2. Логирование длины каждого имени и средней длины.
3. Поиск имени, ближайшего к средней длине, и удаление клиента.

=== SortCustomersTest
Тест проверяет возможность сортировки клиентов по имени в алфавитном порядке.

**Основные шаги:**
1. Сортировка имен клиентов.
2. Проверка сортировки.

== Конфигурация TestNG (testng.xml)
Проект использует TestNG для параллельного выполнения тестов. Конфигурация позволяет запускать тесты с помощью файла `testng.xml`:

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="TestSuite" parallel="tests" thread-count="8">
    <test name="Test1">
        <classes>
            <class name="AddCustomerTest"/>
        </classes>
    </test>
    <test name="Test2">
        <classes>
            <class name="SortCustomersTest"/>
        </classes>
    </test>
    <test name="Test3">
        <classes>
            <class name="DeleteCustomerTest"/>
        </classes>
    </test>
</suite>
```

== Запуск тестов
Для запуска тестов необходимо выполнить команду:
```
mvn clean test  -Dsurefire.suiteXmlFiles=testng.xml -Dallure.results.directory=target/allure-results
```
Эта команда запустит все тесты согласно настройкам `testng.xml`.

== Отчет Allure
Для генерации отчета Allure выполните следующие команды:
```
mvn allure:serve
```
Эта команда откроет Allure отчет в браузере, где вы сможете просмотреть результаты тестов с подробными шагами и описаниями.

== Заключение
Проект автоматизации построен на основе лучших практик, включая Page Object Model, использование утилитных классов, параллельное выполнение тестов с TestNG и интеграцию с Allure для отчетности. Данная структура обеспечивает надежное, гибкое и масштабируемое тестирование веб-приложения.
